name: Build MSYS2 package

on:
  workflow_call:
    inputs:
      package_name:
        description: "Package name to build"
        type: string
      needs:
        description: "Parent workflow job dependencies"
        type: string
      dependencies:
        description: "Install additional dependencies"
        type: string
        default: ""
      packages_repository:
        description: "MSYS2 packages repository to build from"
        type: string
        default: "Windows-on-ARM-Experiments/MSYS2-packages"
      packages_branch:
        description: "MSYS2 packages branch to build from"
        type: string
        default: "woarm64"

defaults:
  run:
    shell: msys2 {0}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup packages repository
        run: |
          `cygpath "${{ github.workspace }}"`/.github/scripts/setup-repository.sh

      - name: Install dependencies
        run: |
          pacman -S --noconfirm \
            base-devel \
            git \
            ccache \
            mingw-w64-x86_64-github-cli \
            mingw-w64-x86_64-jq \
            ${{ inputs.dependencies }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Ccache
        run: |
          `cygpath "${{ github.workspace }}"`/.github/scripts/enable-ccache.sh
          #CCACHE_PATH=`cygpath "${{ github.workspace }}"`/ccache
          CCACHE_PATH=~/ccache
          echo "CCACHE_PATH=$CCACHE_PATH" >> $GITHUB_ENV
          echo $CCACHE_PATH
          mkdir $CCACHE_PATH

      - name: Ccache
        id: cache-ccache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/ccache
          key: main-ccache

      - name: Checkout ${{ inputs.packages_repository }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.packages_repository }}
          ref: ${{ inputs.packages_branch }}
          path: ${{ github.workspace }}/packages

      - name: Download artifacts
        if: ${{ inputs.needs }}
        run: |
          `cygpath "${{ github.workspace }}"`/.github/scripts/download-artifacts.sh ${{ github.run_id }} '${{ inputs.needs }}'

      - name: Install artifacts
        if: ${{ inputs.needs }}
        run: |
          `cygpath "${{ github.workspace }}"`/.github/scripts/install-artifacts.sh

      - name: Copy missing headers for mingw-w64-cross-crt
        if: ${{ inputs.package_name == 'mingw-w64-cross-crt' }}
        run: |
          `cygpath "${{ github.workspace }}"`/.github/scripts/pthread-headers-hack.sh          

      - name: Build ${{ inputs.package_name }}
        working-directory: ${{ github.workspace }}/packages/${{ inputs.package_name }}
        run: |
          ls -al $CCACHE_PATH
          makepkg --syncdeps --rmdeps --cleanbuild --noconfirm --noprogressbar --nocheck --force

      - name: Upload ${{ inputs.package_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package_name }}
          retention-days: 1
          path: ${{ github.workspace }}/packages/${{ inputs.package_name }}/*.pkg.tar.zst
