name: Build MinGW and MSYS2 toolchain

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      msys2_packages_branch:
        description: "MSYS2-packages branch to build"
        type: string
        required: false
        default: "woarm64"

jobs:
  mingw-w64-cross-headers:
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: mingw-w64-cross-headers
      packages_repository: Windows-on-ARM-Experiments/MSYS2-packages
      packages_branch: ${{ github.event.inputs.msys2_packages_branch || 'woarm64' }}

  mingw-w64-cross-binutils:
    needs: mingw-w64-cross-headers
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: mingw-w64-cross-binutils
      needs: ${{ toJson(needs) }}
      packages_repository: Windows-on-ARM-Experiments/MSYS2-packages
      packages_branch: ${{ github.event.inputs.msys2_packages_branch || 'woarm64' }}

  mingw-w64-cross-gcc-stage1:
    needs: [mingw-w64-cross-headers, mingw-w64-cross-binutils]
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: mingw-w64-cross-gcc-stage1
      needs: ${{ toJson(needs) }}
      packages_repository: Windows-on-ARM-Experiments/MSYS2-packages
      packages_branch: ${{ github.event.inputs.msys2_packages_branch || 'woarm64' }}

  mingw-w64-cross-windows-default-manifest:
    needs: [mingw-w64-cross-binutils, mingw-w64-cross-gcc-stage1]
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: mingw-w64-cross-windows-default-manifest
      needs: ${{ toJson(needs) }}
      packages_repository: Windows-on-ARM-Experiments/MSYS2-packages
      packages_branch: ${{ github.event.inputs.msys2_packages_branch || 'woarm64' }}

  mingw-w64-cross-crt:
    needs:
      [
        mingw-w64-cross-headers,
        mingw-w64-cross-binutils,
        mingw-w64-cross-gcc-stage1,
      ]
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: mingw-w64-cross-crt
      needs: ${{ toJson(needs) }}
      dependencies: mingw-w64-cross-winpthreads
      packages_repository: Windows-on-ARM-Experiments/MSYS2-packages
      packages_branch: ${{ github.event.inputs.msys2_packages_branch || 'woarm64' }}

  mingw-w64-cross-winpthreads:
    needs:
      [
        mingw-w64-cross-headers,
        mingw-w64-cross-binutils,
        mingw-w64-cross-gcc-stage1,
        mingw-w64-cross-crt,
      ]
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: mingw-w64-cross-winpthreads
      needs: ${{ toJson(needs) }}
      packages_repository: Windows-on-ARM-Experiments/MSYS2-packages
      packages_branch: ${{ github.event.inputs.msys2_packages_branch || 'woarm64' }}

  mingw-w64-cross-gcc:
    needs:
      [
        mingw-w64-cross-headers,
        mingw-w64-cross-binutils,
        mingw-w64-cross-gcc-stage1,
        mingw-w64-cross-windows-default-manifest,
        mingw-w64-cross-crt,
        mingw-w64-cross-winpthreads,
      ]
    uses: ./.github/workflows/build-package.yml
    with:
      package_name: mingw-w64-cross-gcc
      needs: ${{ toJson(needs) }}
      packages_repository: Windows-on-ARM-Experiments/MSYS2-packages
      packages_branch: ${{ github.event.inputs.msys2_packages_branch || 'woarm64' }}

  repository:
    needs:
      [
        mingw-w64-cross-headers,
        mingw-w64-cross-binutils,
        mingw-w64-cross-gcc-stage1,
        mingw-w64-cross-windows-default-manifest,
        mingw-w64-cross-crt,
        mingw-w64-cross-winpthreads,
        mingw-w64-cross-gcc,
      ]
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true

      - name: Download mingw-w64-cross-headers
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-cross-headers

      - name: Download mingw-w64-cross-binutils
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-cross-binutils

      - name: Download mingw-w64-cross-gcc-stage1
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-cross-gcc-stage1

      - name: Download mingw-w64-cross-windows-default-manifest
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-cross-windows-default-manifest

      - name: Download mingw-w64-cross-crt
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-cross-crt

      - name: Download mingw-w64-cross-winpthreads
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-cross-winpthreads

      - name: Download mingw-w64-cross-gcc
        uses: actions/download-artifact@v4
        with:
          name: mingw-w64-cross-gcc

      - name: Setup MSYS2 packages repository
        run: |
          mkdir aarch64
          mkdir x86_64

          mv -f *-x86_64.pkg.tar.zst x86_64/

          cd x86_64
          repo-add woarm64.db.tar.gz *.pkg.tar.zst

      - name: Create index.html
        run: |
          echo "<!DOCTYPE html><head></head><body></body>" > index.html

      - name: Upload woarm64-msys2-repository
        uses: actions/upload-pages-artifact@v3
        with:
          name: woarm64-msys2-repository
          retention-days: 1
          path: "."

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [repository]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    defaults:
      run:
        shell: bash {0}

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: woarm64-msys2-repository

  check-repository:
    needs: [deploy]
    uses: ./.github/workflows/check-repository.yml
