name: Build MinGW and MSYS2 toolchain

on:
    workflow_dispatch:
      inputs:
        msys2_packages_branch:
          description: 'MSYS2-packages branch to build'
          required: false
          default: 'woarm64'

jobs:
    mingw-w64-cross-headers:
        runs-on: windows-latest
        
        steps:
            - name: Checkout MSYS2 packages repository
              uses: actions/checkout@v4
              with:
                repository: Windows-on-ARM-Experiments/MSYS2-packages
                ref: ${{ github.event.inputs.msys2_packages_branch }}

            - name: Test
              run: echo "Hello World!"
